name: Install Build Dependencies
description: Installs dependencies for Godot build

inputs:
  platform:
    description: 'Target platform'
    required: true
  emsdk_version:
    description: 'Emscripten SDK version'
    required: false
    default: '4.0.22'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies (Linux)
      if: inputs.platform == 'linuxbsd'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config yasm libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev libwayland-dev


    - name: Install SCons (Linux & macOS)
      if: inputs.platform != 'windows'
      shell: bash
      run: python3 -m pip install --no-cache-dir --break-system-packages scons


    - name: Setup Dependencies (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      working-directory: godot
      run: misc/scripts/install_vulkan_sdk_macos.sh


    - name: Setup Emscripten (Web)
      if: inputs.platform == 'web'
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emsdk_version }}


    - name: Install Scons (Windows)
      if: inputs.platform == 'windows'
      shell: cmd
      run: python -m pip install --no-cache-dir scons

    - name: Setup MSVC (Windows)
      if: inputs.platform == 'windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        sdk: 10.0.22621.0
        toolset: 14.23

    - name: Setup Direct3D12 (Windows)
      if: inputs.platform == 'windows'
      shell: cmd
      working-directory: godot
      run: python misc/scripts/install_d3d12_sdk_windows.py
